INSERT INTO `ADVERSAIRE` (`id`, `libelle`, `logo`, `id_STADE`) VALUES
(1, 'AC Ajaccio', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500765.png', 2),
(2, 'GFC Ajaccio', 'http://www.lfp.fr/images/photos/clubs/logo/grand/546836.png', 3),
(3, 'Amiens SC', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500240.png', 4),
(4, 'AJ Auxerre', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500220.png', 5),
(5, 'FC Bourg-en-Bresse 01', 'http://www.lfp.fr/images/photos/clubs/logo/grand/504281.png', 6),
(6, 'Stade Brestois 29', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500024.png', 7),
(7, 'Clermont Foot', 'http://www.lfp.fr/images/photos/clubs/logo/grand/535789.png', 8),
(8, 'Stade Lavallois', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500016.png', 9),
(9, 'Le Havre AC', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500052.png', 10),
(10, 'RC Lens', 'http://www.lfp.fr/images/photos/clubs/logo/grand/RC_LENS_LOGO.png', 11),
(11, 'Nîmes Olympique', 'http://www.lfp.fr/images/photos/clubs/logo/grand/503313.png', 12),
(12, 'Chamois Niortais', 'http://www.lfp.fr/images/photos/clubs/logo/grand/506978.png', 13),
(13, 'US Orléans', 'http://www.lfp.fr/images/photos/clubs/logo/grand/504891_orleans.png', 14),
(14, 'Red Star FC', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500002.png', 15),
(15, 'Stade de Reims', 'http://www.lfp.fr/images/photos/clubs/logo/grand/Stade_reims.png', 16),
(16, 'FC Sochaux-Montbéliard', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500303.png', 17),
(17, 'Tours FC', 'http://www.lfp.fr/images/photos/clubs/logo/grand/504917.png', 18),
(18, 'ES Troyes AC', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500073.png', 19),
(19, 'Valenciennes FC', 'http://www.lfp.fr/images/photos/clubs/logo/grand/500250.png', 20);