INSERT INTO `PRODUIT` (`id`, `nom`, `image`, `prix`, `description`) VALUES
(1, 'Maillot Domicile 16/17 Adulte', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/vad%20maillot%20home.jpg', 70, 'Le maillot domicile du RC Strasbourg !'),
(2, 'Maillot Away 16/17 Adulte', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/vad%20maillot%20away.jpg', 70, 'Le maillot extérieur du RC Strasbourg !'),
(3, 'Maillot Third 16/17 Adulte', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/vad%20maillot%20third.jpg', 70, 'Le maillot third du RC Strasbourg !'),
(4, 'Sweat entraînement 16/17', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/VAD%20sweat%20entrainement.jpg', 45, 'Sweat d\'entraînement du RC Strasbourg !'),
(5, 'T-shirt entraînement Blanc 16-17', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/VAD%20tshirt%20entrainement%20blanc.jpg', 15, 'T-Shirt d\'entraînement blanc'),
(6, 'Ballon 16/17', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/VAD%20ballon%20RCSA.jpg', 20, 'Ballon bleu, idéal pour s\'amuser dans le jardin'),
(7, 'Drapeau bleu 16/17', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/VAD%20drapeau%20bleu.jpg', 15, 'Joli drapeau bleu'),
(8, 'Drapeau blanc 16/17', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/VAD%20drapeau%20blanc.jpg', 15, 'Joli drapeau blanc'),
(9, 'Chope de bière 0,20 L', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/VAD%20bie%CC%80re.jpg', 10, 'Pour boire une bonne bière alsacienne devant les matchs du Racing !'),
(10, 'Mini Fanion blanc', 'https://www.boutique.rcstrasbourgalsace.fr/sites/rcstrasbourg7.ap2s.fr/files/styles/node-merch-product-visuel/public/VAD%20fanion%20blanc.jpg', 5, 'Joli fanion à accrocher à son rétroviseur');