INSERT INTO `PERSONNEL` (`id`, `nom`, `prenom`, `dateNaiss`, `lieuNaiss`, `biographie`, `id_NATIONALITE`, `id_PHOTO`) VALUES
(1, 'Hausherr', 'Victor', '1997-09-18', 'Colmar', 'La chance', 1, NULL),
(2, 'Kammerer', 'Timothée', '1997-12-26', 'Colmar', 'Test', 1, NULL),
(3, 'Kanawati', 'Samy', '1991-09-11', 'Forbach', 'Maître course', 1, NULL),
(4, 'Joya Borja', 'Juan', '1962-01-05', 'Séville', 'Fondateur du club', 2, NULL),
(5, 'BONNEFOI', 'Landry', '1983-09-20', 'Villeparisis', 'Gardien d\'expérience, formé à Cannes et parti très jeune à la Juventus, il est rentré en France où il a été titulaire de nombreuses saisons dans les divisions inférieures. Il est venu l\'été dernier à Strasbourg apporter son expérience en tant que doublure.', 1, 1),
(6, 'OUKIDJA', 'Alexandre', '1988-07-19', 'Nevers', 'Formé à Gueugnon et passé longuement par Lille où il n\'a jamais joué, il est ensuite parti chercher une place de titulaire à Bayonne puis Mouscron. Débarqué à Strasbourg en 2014 en tant que doublure de Gauclin, il a rapidement gagné sa place de titulaire, qu\'il n\'a plus quitté depuis.', 1, 2),
(7, 'SCHMITTHEISSLER', 'Corentin', '1997-04-22', 'Strasbourg', 'Jeune gardien, qui a joué dans toutes les équipes du centre de formation du RCS où il est désormais troisième gardien.', 1, 3),
(8, 'GAMBETTA', 'Andréa', '1996-08-13', 'Lyon', 'Formé à Nice, il est le quatrième gardien du Racing.', 1, 4),
(9, 'N\'DOUR', 'Abdallah', '1993-12-20', 'Rufisque (SEN.)', 'Formé à Metz où il n\'a pas eu sa chance, il a lancé sa carrière à Strasbourg depuis son arrivée en 2014.', 3, 5),
(10, 'MANGANE', 'Kader', '1983-03-23', 'Thiès (SEN.)', 'Expérimenté défenseur de Ligue 1, réputé pour son impact physique et sa dureté dans les duels, il a suivi son entraîneur Thierry Laurey d\'Ajaccio à l\'Alsace.', 3, 6),
(11, 'SALMIER', 'Yoann', '1992-11-21', 'Villiers-le-Bel', 'Venu des bas fonds du foot français en 2014, il a progressé et gagné en temps de chaque saison depuis...', 1, 7),
(12, 'SEKA', 'Ernest', '1987-06-22', 'Cliche-la-Garenne', 'Solide défenseur de National à son arrivée, il s\'est imposé comme le roc de la défense strasbourgeoise et comme un capitaine exemplaire.', 1, 8),
(13, 'SAAD', 'Felipe', '1983-09-11', 'Santos (BRE.)', 'Depuis son arrivée en France, il a connu de nombreux clubs de Ligue 2 ou de Ligue 1 avant de débarquer à Strasbourg en 2015. Titulaire lors de sa première saison, il a peu à peu perdu sa place...', 4, 9),
(14, 'MARESTER', 'Eric', '1984-06-12', 'Villeneuve-la-Garenne', 'Grand habitué de la Ligue 2 avec Troyes, Monaco ou encore Auxerre, il est venu apporter son expérience de la division au Racing.', 1, 10),
(15, 'NOGUEIRA', 'Vincent', '1988-01-16', 'Besançon', 'Après de nombreuses années à Sochaux, il a tenté l\'aventure américaine à Philadelphie avant de vouloir rentrer en France pour raisons personnelles. Son choix s\'est porté sur le Racing.', 1, 11),
(16, 'GRIMM', 'Jérémy', '1987-03-27', 'Ostheim', 'Formé au Racing il y a une dizaine d\'années, il est parti en Suisse avant de passer cinq ans à Colmar puis de rentrer à la maison où il s\'est imposé comme un cadre du groupe strasbourgeois.', 1, 12),
(17, 'SACKO', 'Ihsan', '1997-07-19', 'Alfortville', 'Formé à Valenciennes, il a refusé de poursuivre dans le Nord pour rejoindre Strasbourg où il s\'est révélé depuis la saison passée.', 1, 13),
(18, 'AHOLOU', 'Jean-Eudes', '1994-03-20', 'Yapougon (CIV.)', 'Passé par Lille et révélé à Orléans, il a rejoint le Racing en janvier dernier pour passer un cap, ce qu\'il semble réussir puisqu\'il s\'est imposé dans l\'entrejeu.', 5, 14),
(19, 'GONÇALVES', 'Anthony', '1986-03-06', 'Chartres', 'Après une carrière professionnelle entièrement passée à Laval, il a quitté son club pour rejoindre l\'Alsace où il est là aussi considéré comme un titulaire.', 1, 15),
(20, 'NDOYE', 'Mayoro', '1991-12-18', 'Mbao (SEN)', 'Comme N\'Dour, il est venu du Sénégal à Metz, où il disputé plusieurs saisons en National et en Ligue 2. Il a ensuite rejoint Strasbourg pour jouer un rôle de complément.', 3, 16),
(21, 'DOS SANTOS', 'Laurent', '1993-03-21', 'Montmorencey', 'Après trois saisons à Guingamp où il a peu joué, il est venu à Strasbourg où il est venu faire profiter de sa polyvalence au milieu et en défense.', 1, 17),
(22, 'CACI', 'Anthony', '1997-07-01', 'Forbach', 'Jeune du club, il a déjà disputé quelques matchs en équipe première.', 1, 18),
(23, 'SOLVET', 'Steve', '1996-03-20', 'France', 'Jeune du club, il n\'a pas encore débuté officiellement avec le groupe pro.', 1, 19),
(24, 'WEISSBECK', 'Gaëtan', '1997-01-17', 'Wissembourg', 'Grand espoir du club, il a déjà disputé un match de Coupe de France...', 1, 20),
(25, 'GUILLAUME', 'Baptiste', '1995-06-16', 'Bruxelles (BEL.)', 'Lancé à Lens, il a rejoint le voisin Lillois où il a vite été écarté. Il est venu au RCS pour se relancer et enfin faire décoller sa carrière.', 6, 21),
(26, 'LIENARD', 'Dimitri', '1988-02-13', 'Belfort', 'Venu des divisions inférieurs entre Belfort et Mulhouse, il découvre le monde professionnel à Strasbourg cette saison après de bonnes saisons en National.', 1, 22),
(27, 'BLAYAC', 'Jérémy', '1983-06-13', 'Saint-Affrique', 'Il a connu de nombreux clubs en France où il s\'est imposé comme un solide buteur de Ligue 2. Il est se relancer et finir sa carrière à Strasbourg où il réalise de bonnes saisons.', 1, 23),
(28, 'BAHOKEN', 'Stéphane', '1992-05-28', 'Grasse', 'Formé à Nice où il ne s\'est pas imposé, il a signé à Strasbourg pour progresser mais sans réellement s\'imposer depuis son arrivée en 2014.', 1, 24),
(29, 'GRAGNIC', 'Vincent', '1983-06-23', 'Quimperlé', 'Comme Marester et Gonçalves, il apporte son expérience de la Ligue 2 aux autres joueurs du Racing même s\'il joue peu.', 1, 25),
(30, 'BOUTAIB', 'Khalid', '1987-04-24', 'Bagnols-sur-Cèze', 'Révélé tardivement après de nombreuses saisons dans les divisions amateurs, il a suivi son coach d\'Ajaccio à Strasbourg où il est l\'un des artisans majeurs de la belle saison du club. ', 7, 26),
(31, 'KELLER', 'Marc', '1968-01-14', 'Colmar', 'Joueur dans les années 90 puis dirigeant dans les années 2000 avant de vivre deux expériences délicates à Monaco, il a récupéré le Racing en CFA2 pour le mener jusqu\'à la Ligue 2.', 1, 27),
(32, 'LAUREY', 'Thierry', '1964-02-17', 'Troyes', 'Connaisseur de la Ligue 2, il est venu en Alsace pour réaliser la même prouesse réussie au GFC Ajaccio, à savoir enchaîner une montée en Ligue 2 puis en Ligue 1 en deux saisons.', 1, 28),
(33, 'LEFEVRE', 'Fabien', '1971-11-14', 'Montpellier', 'Ancien coéquipier de Laurey à Montpellier dans les années 90, il a retrouvé ce dernier au GFC Ajaccio en 2015 pour être son entraîneur adjoint avant de la suivre en Alsace un an plus tard.', 1, 29),
(34, 'ROI', 'Sébastien', '1978-08-02', 'Valence', 'Passé par le centre de formation du Racing il y a une vingtaine d\'années, il n\'a connu que le foot amateur avant de revenir au RCS en tant qu\'entraîneur adjoint de François Keller en 2011. Il n\'a pas quitté le poste depuis.', 1, 30),
(35, 'HOURS', 'Jean-Yves', '1964-12-28', 'Alès', 'Comme Lefèvre, il a connu Laurey à Montpellier. Après sa carrière, il a connu les staffs de Sedan, Évian, la Guinée et enfin le Racing.', 1, 31),
(36, 'BAILLEUX', 'Florian', '1987-06-18', 'Boulogne-sur-Mer', 'Après avoir exercé à Boulogne-sur-Mer et Carquefou, il est venu poursuivre sa carrière en Alsace en 2014.', 1, 32),
(37, 'FEIGENBRUGEL', 'Guy', '1974-02-26', 'Strasbourg', 'Il a rejoint le club en 2011 alors qu\'il était en CFA2.', 1, 33),
(38, 'PIETRA', 'François', '1960-05-15', 'Saint-Dizier', 'Médecin historique du club, il occupe le poste depuis 1990', 1, 34),
(39, 'ROTH', 'Antoine', '1986-01-27', 'Dambach-la-Ville', 'Il a rejoint le Racing en 2016.', 1, 35),
(40, 'GARNIER', 'Franck', '1982-09-13', 'Strasbourg', 'Il occupe le poste d’ostéopathe du Racing depuis plusieurs saisons.', 1, 36);